Find product
hoantran1107/Thuc_tap_week_1 pull request #34
Opened 2022-12-14 16:34 UTC by ThanhNgTr

2022-12-14 18:26 UTC, hoantran1107 requested changes

2022-12-14 18:26 UTC, hoantran1107 commented on ShopBanDo/ShopBanDo/Views/Product/Search.cshtml
> +                        <a href="/">Trang chủ</a>
xua lai tieng anh nha

2022-12-14 18:26 UTC, hoantran1107 commented on ShopBanDo/ShopBanDo/Controllers/ProductController.cs
> +                var Categories = _context.Categories;
phan nay viet repository luon

2022-12-14 18:26 UTC, hoantran1107 commented on ShopBanDo/ShopBanDo/Controllers/ProductController.cs
> +                var Categories = _context.Categories;
xoa try phia tren dum nha

2022-12-14 18:26 UTC, hoantran1107 commented on ShopBanDo/ShopBanDo/Repositories/ProductRepository.cs
> +        public IEnumerable<Product> FindProducts()
gop 2 cai nay lai luon neu key = null thi chay find all product nguoc lai key != null thi tim theo key

2022-12-15 03:03 UTC, xuandat282 approved these changes

2022-12-15 03:56 UTC, ThanhNgTr commented
e vừa sử đổi theo yêu cầu của a rồi đó ạ. A và các bạn vào check đi ạ

2022-12-15 04:12 UTC, hoantran1107 approved these changes

2022-12-15 04:19 UTC, hoantran1107 approved these changes

2022-12-15 04:26 UTC, nhphat12a approved these changes

2022-12-15 04:26 UTC, nhphat12a commented on ShopBanDo/ShopBanDo/Controllers/ProductController.cs
> +            IEnumerable<Product> item;
Hay qua ta

2022-12-15 05:19 UTC, PhuQuocKhanh approved these changes

2022-12-15 05:43 UTC, merged

2022-12-15 07:42 UTC, tranhaiphuoc reviewed
..